spring.appliaction.name=addition
server.port:7070

spring.datasource.url=jdbc:mysql://localhost:3306/addition
spring.datasource.username=root
spring.datasource.password=bca123
sprinf.jpa.hibernate.ddl.auto=update
